### ISSUE TITLE
cristianCeamatu / microverse-Embedding-Images-and-Video-Issues

### ISSUE THREAD

**Issue by AkintoyeOlamide** [cristianCeamatu/microverse-Embedding-Images-and-Video#8]
1. The sidebar should have more videos(at least six videos)
2. We had issues with the comment section also(But a team member was able to assist the presenter to slightly fix the issue till our time got completed). 
3. The snapshot wasn't well arranged.
4. The whole webpage seemed jam-packed, but the presenter worked on arranging it with his partner.

**Comment by cristianCeamatu** [comment]
1. The sidebar should have more videos(at least six videos) -  We will add more video after we finish the styling.
2. We had issues with the comment section also(But a team member was able to assist the presenter to slightly fix the issue till our time got completed) - We found a better fix for the comment section form and now is working.
3. The snapshot wasn't well arranged - We will add the project snapshot at the end when we finish the project, this is a temporary fix snapshot.
4. The whole webpage seemed jam-packed, but the presenter worked on arranging it with his partner. - We are still working on it.

Thank you for your support and finding issues.
